/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersImport } from './routes/users'
import { Route as SignupImport } from './routes/signup'
import { Route as ProfileImport } from './routes/profile'
import { Route as FeedbackImport } from './routes/feedback'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as LoginPageImport } from './routes/LoginPage'
import { Route as FallBackImport } from './routes/FallBack'
import { Route as AdminLoginPageImport } from './routes/AdminLoginPage'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UsersRoute = UsersImport.update({
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const FeedbackRoute = FeedbackImport.update({
  path: '/feedback',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const LoginPageRoute = LoginPageImport.update({
  path: '/LoginPage',
  getParentRoute: () => rootRoute,
} as any)

const FallBackRoute = FallBackImport.update({
  path: '/FallBack',
  getParentRoute: () => rootRoute,
} as any)

const AdminLoginPageRoute = AdminLoginPageImport.update({
  path: '/AdminLoginPage',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/AdminLoginPage': {
      id: '/AdminLoginPage'
      path: '/AdminLoginPage'
      fullPath: '/AdminLoginPage'
      preLoaderRoute: typeof AdminLoginPageImport
      parentRoute: typeof rootRoute
    }
    '/FallBack': {
      id: '/FallBack'
      path: '/FallBack'
      fullPath: '/FallBack'
      preLoaderRoute: typeof FallBackImport
      parentRoute: typeof rootRoute
    }
    '/LoginPage': {
      id: '/LoginPage'
      path: '/LoginPage'
      fullPath: '/LoginPage'
      preLoaderRoute: typeof LoginPageImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AdminLoginPage': typeof AdminLoginPageRoute
  '/FallBack': typeof FallBackRoute
  '/LoginPage': typeof LoginPageRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/users': typeof UsersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AdminLoginPage': typeof AdminLoginPageRoute
  '/FallBack': typeof FallBackRoute
  '/LoginPage': typeof LoginPageRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/users': typeof UsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/AdminLoginPage': typeof AdminLoginPageRoute
  '/FallBack': typeof FallBackRoute
  '/LoginPage': typeof LoginPageRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/users': typeof UsersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/AdminLoginPage'
    | '/FallBack'
    | '/LoginPage'
    | '/dashboard'
    | '/feedback'
    | '/profile'
    | '/signup'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AdminLoginPage'
    | '/FallBack'
    | '/LoginPage'
    | '/dashboard'
    | '/feedback'
    | '/profile'
    | '/signup'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/AdminLoginPage'
    | '/FallBack'
    | '/LoginPage'
    | '/dashboard'
    | '/feedback'
    | '/profile'
    | '/signup'
    | '/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginPageRoute: typeof AdminLoginPageRoute
  FallBackRoute: typeof FallBackRoute
  LoginPageRoute: typeof LoginPageRoute
  DashboardRoute: typeof DashboardRoute
  FeedbackRoute: typeof FeedbackRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  UsersRoute: typeof UsersRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginPageRoute: AdminLoginPageRoute,
  FallBackRoute: FallBackRoute,
  LoginPageRoute: LoginPageRoute,
  DashboardRoute: DashboardRoute,
  FeedbackRoute: FeedbackRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  UsersRoute: UsersRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/AdminLoginPage",
        "/FallBack",
        "/LoginPage",
        "/dashboard",
        "/feedback",
        "/profile",
        "/signup",
        "/users"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/AdminLoginPage": {
      "filePath": "AdminLoginPage.tsx"
    },
    "/FallBack": {
      "filePath": "FallBack.tsx"
    },
    "/LoginPage": {
      "filePath": "LoginPage.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/feedback": {
      "filePath": "feedback.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/users": {
      "filePath": "users.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
